spring:
  profiles:
    active: prod
#    active: dev

--- #dev
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driverClassName: org.h2.Driver
    username: sa
    password:

--- #prod
spring:
  config:
    activate:
      on-profile: prod

  #Maria DB
  datasource:
    url: jdbc:mariadb://rds-maria.c8dkd6mpemsb.ap-northeast-2.rds.amazonaws.com:3306/project
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: Password12!


  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

        show_sql: true

        format_sql: true

        use_sql_comments: true
    hibernate:
      ddl-auto: create


server:
  port: 8081