spring:
  profiles:
    active: prod
#    active: dev
    # include oauth property file
    include: oauth

server:
  port: 8081

# jasypt config (2021-04-13 12:13:39)
jasypt:
  encryptor:
    bean: jasyptStringEncryptor


--- #dev
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driverClassName: org.h2.Driver
    username: sa
    password:

# front uri
front-uri: http://localhost:3000

--- #prod
spring:
  config:
    activate:
      on-profile: prod

  #Maria DB
  datasource:
    url: jdbc:mariadb://rds-maria.c8dkd6mpemsb.ap-northeast-2.rds.amazonaws.com:3306/project
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: ENC(S3sT9e6IKbjByJo7Z+wfFDkhL2AZFMun)


  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

        show_sql: true

        format_sql: true

        use_sql_comments: true
    hibernate:
      ddl-auto: create

# front uri
front-uri: http://localhost:3000
