spring:
  profiles:
    active: prod
#    active: dev

--- #dev
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driverClassName: org.h2.Driver
    username: sa
    password:

--- #prod
spring:
  config:
    activate:
      on-profile: prod

  #Maria DB
  datasource:
    url: jdbc:mariadb://rds-maria.c8dkd6mpemsb.ap-northeast-2.rds.amazonaws.com:3306/project
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: Password12!

  #JPA 설정
  jpa:
    open-in-view: false
    #    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        #하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력해 준다.
        show_sql: true
        #콘솔에 출력되는 JPA 실행 쿼리를 가독성있게 표현한다.
        format_sql: true
        #디버깅이 용이하도록 SQL문 이외에 추가적인 정보를 출력해 준다.
        use_sql_comments: true


server:
  port: 8081